builders:
  _aggregate_database:
    import: tool/src/aggregate_database.dart
    builder_factories:
      - aggregateDatabase
    build_extensions:
      $lib$:
        - src/all_units.dart
        - src/all_upgrades.dart
        - src/all_weapons.dart
    build_to: source
    auto_apply: root_package
    required_inputs:
      - lib/src/model/**.g.dart
  _aggregate_constants:
    import: tool/src/aggregate_constants.dart
    builder_factories:
      - aggregateConstants
    build_extensions:
      "src/model/keyword.dart":
        - "keyword.aggregate.dart"
      "src/model/wave.dart":
        - "wave.aggregate.dart"
    build_to: source
    auto_apply: root_package
  _generate_thumbs:
    import: tool/src/generate_thumbnails.dart
    builder_factories:
      - generateThumbnails
    build_extensions:
      ".png":
        - ".thumb.png"
    build_to: source
    auto_apply: root_package
