name: swlegion

homepage: https://github.com/hquplink/swlegion
description: 'Database and Data Model for Star Wars: Legion'
authors:
  - Matan Lurey <matan@hquplink.com>
version: 0.1.0-alpha+4
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_collection: ^4.0.0
  built_value: ^6.1.6
  meta: ^1.1.6

dev_dependencies:
  build_runner: ^1.1.2
  built_value_generator: ^6.1.6
  test: ^1.5.1
