name: swlegion

homepage: https://github.com/hquplink/swlegion
description: "JSON-Serializable Data Model and Card Database for Star Wars: Legion"
authors:
  - Matan Lurey <matan@hquplink.com>
version: 0.4.0
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  args: ^1.5.1
  built_collection: ^4.0.0
  built_value: ^6.1.6
  collection: ^1.14.11
  meta: ^1.1.6

dev_dependencies:
  analyzer: ^0.34.2
  build: ^1.0.2
  build_runner: ^1.1.2
  built_value_generator: ^6.1.6
  glob: ^1.1.7
  path: ^1.6.2
  test: ^1.5.1
  yaml: ^2.1.15
